name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Oh hi! Seems this is your first time making an iseue in this repo... HOW MANY DO I HAVE????"
        pr-message: "This is your first time trying to fix somrthing in this repo. Let's hope you are a good coder!"
